<a href="https://colab.research.google.com/github/prithvi2226/Webscrap-Basic/blob/master/spamclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SPAM CLASSIFIER

In [0]:
#This program detects if an email is a spam(1) or not(0)

In [0]:
#importing libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [6]:
#Load data
from google.colab import files
uploaded = files.upload()


Saving emails.csv to emails.csv


In [7]:
#read the csv
df_1 = pd.read_csv("emails.csv")
#display first 5 elements
df_1.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [8]:
#determine the shape of the dataset
df_1.shape

(5728, 2)

In [9]:
#what are the columns
df_1.columns

Index(['text', 'spam'], dtype='object')

In [0]:
#remove all the duplicates
df_1.drop_duplicates(inplace = True)


In [11]:
#new shape(No od columns and rows)
df_1.shape

(5695, 2)

In [12]:
#sh0w the no of missing data for each column
df_1.isnull().sum()

text    0
spam    0
dtype: int64

In [13]:
#download stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
def process_text(text):
  #1 remove punctuation
  #2 remove stopwords
  #3 give out the clean text

  #1 TO remove the punctuation
  no_punc = [char for char in text if char not in string.punctuation]
  no_punc = ''.join(no_punc)
  
  #2 To remove english stopwords
  clean_words = [word for word in no_punc.split() if word.lower() not in stopwords.words('english')]
  
  #3 Return clean text of words
  return clean_words


In [15]:
#show the tokenization(list of tokens called lemmas)
df_1['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [17]:
#Example

message4 = 'hello hello world one world play'
message5 = 'play ready play hello one world'
print(message4)
print()

#convert the text to matrix form of tokens using CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer = process_text).fit_transform([[message4], [message5]])
print(bow4)
print()

print(bow4.shape)

hello hello world one world play

  (0, 0)	2
  (0, 4)	2
  (0, 1)	1
  (0, 2)	1
  (1, 0)	1
  (1, 4)	1
  (1, 1)	1
  (1, 2)	2
  (1, 3)	1

(2, 5)


In [0]:
#convert actual data texts to a matrix tokens
from sklearn.feature_extraction.text import CountVectorizer
message_bow = CountVectorizer(analyzer = process_text).fit_transform(df_1['text'])


In [0]:
#split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(message_bow, df_1['spam'], test_size = 0.20, random_state = 0)

In [21]:
#get the shape of message_bow
message_bow.shape

(5695, 37229)

In [0]:
#create and train the naive bayes classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train,y_train)

In [26]:
#print the predictions
print(classifier.predict(X_train))

#print the actual values
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [27]:
#evaluate the model on training dataset
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
pred = classifier.predict(X_train)
print(classification_report(y_train, pred))
print()
print("confusion matrix : \n", confusion_matrix(y_train, pred) )
print()
print("accuracy: \n", accuracy_score(y_train, pred))
#that is done for the training set

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


confusion matrix : 
 [[3445   12]
 [   1 1098]]

accuracy: 
 0.9971466198419666


In [28]:
#for the test dataset
#print the predictions
print(classifier.predict(X_test))

#print the actual values
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [29]:
#evaluate the model on test dataset
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
pred = classifier.predict(X_test)
print(classification_report(y_test, pred))
print()
print("confusion matrix : \n", confusion_matrix(y_test, pred) )
print()
print("accuracy: \n", accuracy_score(y_test, pred))


              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


confusion matrix : 
 [[862   8]
 [  1 268]]

accuracy: 
 0.9920983318700615
